[build]
builder = "nixpacks"
installCommand = "pnpm install --no-frozen-lockfile"
buildCommand = "pnpm run -C artifacts/fanta11 build && pnpm run -C artifacts/api-server build"

[deploy]
startCommand = "node --enable-source-maps /app/artifacts/api-server/dist/index.mjs"

[variables]
NIXPACKS_NODE_VERSION = "20"
