/**
 * seed-wc-players.ts — Fully static World Cup 2026 player pool
 * No API calls. All 32 nations, hardcoded real squads.
 *
 * Run: pnpm --filter @workspace/scripts run seed-wc-players
 */

import { db, playersTable, teamsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

type Pos = "GK" | "DEF" | "MID" | "FWD";
type P = { name: string; pos: Pos; price: number };
type Nation = { name: string; code: string; players: P[] };

const NATIONS: Nation[] = [
  // ── 1. Argentina ──────────────────────────────────────────────────────────
  { name: "Argentina", code: "ARG", players: [
    { name: "Emiliano Martínez",  pos: "GK",  price: 6.0 },
    { name: "Gerónimo Rulli",     pos: "GK",  price: 4.5 },
    { name: "Juan Musso",         pos: "GK",  price: 4.5 },
    { name: "Nicolás Tagliafico", pos: "DEF", price: 5.5 },
    { name: "Cristian Romero",    pos: "DEF", price: 6.5 },
    { name: "Lisandro Martínez",  pos: "DEF", price: 6.5 },
    { name: "Nahuel Molina",      pos: "DEF", price: 6.0 },
    { name: "Marcos Acuña",       pos: "DEF", price: 5.5 },
    { name: "Rodrigo De Paul",    pos: "MID", price: 8.0 },
    { name: "Alexis Mac Allister",pos: "MID", price: 8.0 },
    { name: "Enzo Fernández",     pos: "MID", price: 8.5 },
    { name: "Giovani Lo Celso",   pos: "MID", price: 7.0 },
    { name: "Lionel Messi",       pos: "FWD", price: 12.5 },
    { name: "Lautaro Martínez",   pos: "FWD", price: 9.0 },
    { name: "Ángel Di María",     pos: "FWD", price: 7.5 },
    { name: "Julián Álvarez",     pos: "FWD", price: 9.5 },
  ]},
  // ── 2. France ─────────────────────────────────────────────────────────────
  { name: "France", code: "FRA", players: [
    { name: "Mike Maignan",         pos: "GK",  price: 5.5 },
    { name: "Hugo Lloris",          pos: "GK",  price: 5.0 },
    { name: "Alphonse Areola",      pos: "GK",  price: 4.5 },
    { name: "Théo Hernandez",       pos: "DEF", price: 7.0 },
    { name: "Raphaël Varane",       pos: "DEF", price: 6.0 },
    { name: "Ibrahima Konaté",      pos: "DEF", price: 6.5 },
    { name: "Benjamin Pavard",      pos: "DEF", price: 6.0 },
    { name: "William Saliba",       pos: "DEF", price: 7.0 },
    { name: "Antoine Griezmann",    pos: "MID", price: 9.0 },
    { name: "Aurélien Tchouaméni",  pos: "MID", price: 7.5 },
    { name: "Eduardo Camavinga",    pos: "MID", price: 7.5 },
    { name: "Adrien Rabiot",        pos: "MID", price: 6.5 },
    { name: "Kylian Mbappé",        pos: "FWD", price: 13.5 },
    { name: "Ousmane Dembélé",      pos: "FWD", price: 8.5 },
    { name: "Olivier Giroud",       pos: "FWD", price: 7.0 },
    { name: "Marcus Thuram",        pos: "FWD", price: 8.0 },
  ]},
  // ── 3. Brazil ─────────────────────────────────────────────────────────────
  { name: "Brazil", code: "BRA", players: [
    { name: "Alisson Becker",   pos: "GK",  price: 6.0 },
    { name: "Ederson",          pos: "GK",  price: 5.5 },
    { name: "Weverton",         pos: "GK",  price: 4.5 },
    { name: "Danilo",           pos: "DEF", price: 5.5 },
    { name: "Éder Militão",     pos: "DEF", price: 6.5 },
    { name: "Marquinhos",       pos: "DEF", price: 7.0 },
    { name: "Alex Sandro",      pos: "DEF", price: 5.5 },
    { name: "Bremer",           pos: "DEF", price: 6.0 },
    { name: "Casemiro",         pos: "MID", price: 7.5 },
    { name: "Rodrygo",          pos: "MID", price: 9.0 },
    { name: "Lucas Paquetá",    pos: "MID", price: 8.0 },
    { name: "Gerson",           pos: "MID", price: 6.5 },
    { name: "Vinícius Júnior",  pos: "FWD", price: 13.0 },
    { name: "Neymar Jr",        pos: "FWD", price: 11.0 },
    { name: "Richarlison",      pos: "FWD", price: 8.5 },
    { name: "Raphinha",         pos: "FWD", price: 9.5 },
  ]},
  // ── 4. England ────────────────────────────────────────────────────────────
  { name: "England", code: "ENG", players: [
    { name: "Jordan Pickford",       pos: "GK",  price: 5.0 },
    { name: "Aaron Ramsdale",        pos: "GK",  price: 4.5 },
    { name: "Nick Pope",             pos: "GK",  price: 4.5 },
    { name: "Trent Alexander-Arnold",pos: "DEF", price: 7.0 },
    { name: "Harry Maguire",         pos: "DEF", price: 5.5 },
    { name: "John Stones",           pos: "DEF", price: 6.0 },
    { name: "Luke Shaw",             pos: "DEF", price: 6.0 },
    { name: "Kieran Trippier",       pos: "DEF", price: 6.5 },
    { name: "Jude Bellingham",       pos: "MID", price: 11.5 },
    { name: "Declan Rice",           pos: "MID", price: 8.5 },
    { name: "Bukayo Saka",           pos: "MID", price: 10.5 },
    { name: "Phil Foden",            pos: "MID", price: 10.0 },
    { name: "Harry Kane",            pos: "FWD", price: 11.0 },
    { name: "Marcus Rashford",       pos: "FWD", price: 8.5 },
    { name: "Raheem Sterling",       pos: "FWD", price: 7.5 },
    { name: "Ollie Watkins",         pos: "FWD", price: 8.0 },
  ]},
  // ── 5. Spain ──────────────────────────────────────────────────────────────
  { name: "Spain", code: "ESP", players: [
    { name: "Unai Simón",        pos: "GK",  price: 5.0 },
    { name: "David Raya",        pos: "GK",  price: 5.0 },
    { name: "Robert Sánchez",    pos: "GK",  price: 4.5 },
    { name: "Dani Carvajal",     pos: "DEF", price: 6.5 },
    { name: "Aymeric Laporte",   pos: "DEF", price: 6.0 },
    { name: "Robin Le Normand",  pos: "DEF", price: 6.0 },
    { name: "Jordi Alba",        pos: "DEF", price: 5.5 },
    { name: "José Gayà",         pos: "DEF", price: 5.5 },
    { name: "Pedri",             pos: "MID", price: 9.5 },
    { name: "Gavi",              pos: "MID", price: 8.5 },
    { name: "Rodri",             pos: "MID", price: 9.0 },
    { name: "Dani Olmo",         pos: "MID", price: 8.0 },
    { name: "Álvaro Morata",     pos: "FWD", price: 8.0 },
    { name: "Ferran Torres",     pos: "FWD", price: 7.5 },
    { name: "Lamine Yamal",      pos: "FWD", price: 11.0 },
    { name: "Marco Asensio",     pos: "FWD", price: 7.5 },
  ]},
  // ── 6. Portugal ───────────────────────────────────────────────────────────
  { name: "Portugal", code: "POR", players: [
    { name: "Diogo Costa",        pos: "GK",  price: 5.0 },
    { name: "Rui Patrício",       pos: "GK",  price: 4.5 },
    { name: "José Sá",            pos: "GK",  price: 4.5 },
    { name: "João Cancelo",       pos: "DEF", price: 7.0 },
    { name: "Pepe",               pos: "DEF", price: 5.5 },
    { name: "Rúben Dias",         pos: "DEF", price: 7.0 },
    { name: "Raphaël Guerreiro",  pos: "DEF", price: 6.0 },
    { name: "Nelson Semedo",      pos: "DEF", price: 6.0 },
    { name: "Bernardo Silva",     pos: "MID", price: 9.0 },
    { name: "Vitinha",            pos: "MID", price: 7.5 },
    { name: "Rúben Neves",        pos: "MID", price: 7.0 },
    { name: "João Moutinho",      pos: "MID", price: 6.0 },
    { name: "Cristiano Ronaldo",  pos: "FWD", price: 9.5 },
    { name: "João Félix",         pos: "FWD", price: 8.5 },
    { name: "Rafael Leão",        pos: "FWD", price: 9.5 },
    { name: "Ricardo Horta",      pos: "FWD", price: 6.5 },
  ]},
  // ── 7. Germany ────────────────────────────────────────────────────────────
  { name: "Germany", code: "GER", players: [
    { name: "Manuel Neuer",          pos: "GK",  price: 5.0 },
    { name: "Marc-André ter Stegen", pos: "GK",  price: 5.0 },
    { name: "Antonio Rüdiger",       pos: "DEF", price: 6.5 },
    { name: "Nico Schlotterbeck",    pos: "DEF", price: 6.0 },
    { name: "Joshua Kimmich",        pos: "DEF", price: 7.0 },
    { name: "David Raum",            pos: "DEF", price: 6.0 },
    { name: "Robin Gosens",          pos: "DEF", price: 5.5 },
    { name: "Ilkay Gündogan",        pos: "MID", price: 7.5 },
    { name: "Leon Goretzka",         pos: "MID", price: 7.0 },
    { name: "Jamal Musiala",         pos: "MID", price: 9.0 },
    { name: "Florian Wirtz",         pos: "MID", price: 9.0 },
    { name: "Leroy Sané",            pos: "MID", price: 8.0 },
    { name: "Niclas Füllkrug",       pos: "FWD", price: 7.5 },
    { name: "Thomas Müller",         pos: "FWD", price: 7.0 },
    { name: "Karim Adeyemi",         pos: "FWD", price: 7.5 },
  ]},
  // ── 8. Netherlands ────────────────────────────────────────────────────────
  { name: "Netherlands", code: "NED", players: [
    { name: "Bart Verbruggen",   pos: "GK",  price: 5.0 },
    { name: "Remko Pasveer",     pos: "GK",  price: 4.5 },
    { name: "Virgil van Dijk",   pos: "DEF", price: 7.0 },
    { name: "Matthijs de Ligt",  pos: "DEF", price: 6.5 },
    { name: "Stefan de Vrij",    pos: "DEF", price: 6.0 },
    { name: "Denzel Dumfries",   pos: "DEF", price: 6.5 },
    { name: "Nathan Aké",        pos: "DEF", price: 6.0 },
    { name: "Frenkie de Jong",   pos: "MID", price: 7.5 },
    { name: "Ryan Gravenberch",  pos: "MID", price: 7.0 },
    { name: "Tijjani Reijnders", pos: "MID", price: 7.0 },
    { name: "Xavi Simons",       pos: "MID", price: 8.5 },
    { name: "Teun Koopmeiners",  pos: "MID", price: 7.5 },
    { name: "Cody Gakpo",        pos: "FWD", price: 8.5 },
    { name: "Memphis Depay",     pos: "FWD", price: 7.5 },
    { name: "Wout Weghorst",     pos: "FWD", price: 7.0 },
  ]},
  // ── 9. Belgium ────────────────────────────────────────────────────────────
  { name: "Belgium", code: "BEL", players: [
    { name: "Thibaut Courtois",   pos: "GK",  price: 6.0 },
    { name: "Koen Casteels",      pos: "GK",  price: 4.5 },
    { name: "Toby Alderweireld",  pos: "DEF", price: 5.5 },
    { name: "Jan Vertonghen",     pos: "DEF", price: 5.5 },
    { name: "Zeno Debast",        pos: "DEF", price: 6.0 },
    { name: "Arthur Theate",      pos: "DEF", price: 6.0 },
    { name: "Timothy Castagne",   pos: "DEF", price: 5.5 },
    { name: "Kevin De Bruyne",    pos: "MID", price: 10.5 },
    { name: "Youri Tielemans",    pos: "MID", price: 7.0 },
    { name: "Amadou Onana",       pos: "MID", price: 7.0 },
    { name: "Leandro Trossard",   pos: "MID", price: 7.5 },
    { name: "Charles De Ketelaere",pos:"MID", price: 7.5 },
    { name: "Romelu Lukaku",      pos: "FWD", price: 8.5 },
    { name: "Loïs Openda",        pos: "FWD", price: 8.0 },
    { name: "Jeremy Doku",        pos: "FWD", price: 7.5 },
  ]},
  // ── 10. Croatia ───────────────────────────────────────────────────────────
  { name: "Croatia", code: "CRO", players: [
    { name: "Dominik Livaković",  pos: "GK",  price: 5.0 },
    { name: "Ivica Ivušić",       pos: "GK",  price: 4.5 },
    { name: "Joško Gvardiol",     pos: "DEF", price: 7.0 },
    { name: "Dejan Lovren",       pos: "DEF", price: 5.5 },
    { name: "Josip Stanišić",     pos: "DEF", price: 5.5 },
    { name: "Borna Ćaleta-Car",   pos: "DEF", price: 5.0 },
    { name: "Borna Sosa",         pos: "DEF", price: 5.5 },
    { name: "Luka Modrić",        pos: "MID", price: 8.0 },
    { name: "Mateo Kovačić",      pos: "MID", price: 7.5 },
    { name: "Marcelo Brozović",   pos: "MID", price: 7.0 },
    { name: "Nikola Vlašić",      pos: "MID", price: 6.5 },
    { name: "Ivan Perišić",       pos: "MID", price: 6.5 },
    { name: "Andrej Kramarić",    pos: "FWD", price: 8.0 },
    { name: "Bruno Petković",     pos: "FWD", price: 6.5 },
    { name: "Marko Livaja",       pos: "FWD", price: 6.5 },
  ]},
  // ── 11. USA ───────────────────────────────────────────────────────────────
  { name: "USA", code: "USA", players: [
    { name: "Matt Turner",          pos: "GK",  price: 4.5 },
    { name: "Ethan Horvath",        pos: "GK",  price: 4.0 },
    { name: "Sergiño Dest",         pos: "DEF", price: 5.5 },
    { name: "Antonee Robinson",     pos: "DEF", price: 5.5 },
    { name: "Walker Zimmerman",     pos: "DEF", price: 5.0 },
    { name: "Miles Robinson",       pos: "DEF", price: 5.0 },
    { name: "Joe Scally",           pos: "DEF", price: 5.0 },
    { name: "Tyler Adams",          pos: "MID", price: 6.5 },
    { name: "Weston McKennie",      pos: "MID", price: 6.5 },
    { name: "Yunus Musah",          pos: "MID", price: 6.5 },
    { name: "Christian Pulisic",    pos: "MID", price: 8.5 },
    { name: "Gio Reyna",            pos: "MID", price: 7.0 },
    { name: "Folarin Balogun",      pos: "FWD", price: 7.5 },
    { name: "Ricardo Pepi",         pos: "FWD", price: 7.0 },
    { name: "Josh Sargent",         pos: "FWD", price: 6.5 },
  ]},
  // ── 12. Mexico ────────────────────────────────────────────────────────────
  { name: "Mexico", code: "MEX", players: [
    { name: "Guillermo Ochoa",    pos: "GK",  price: 4.5 },
    { name: "Luis Malagón",       pos: "GK",  price: 4.5 },
    { name: "Jorge Sánchez",      pos: "DEF", price: 5.0 },
    { name: "César Montes",       pos: "DEF", price: 5.0 },
    { name: "Johan Vásquez",      pos: "DEF", price: 5.0 },
    { name: "Gerardo Arteaga",    pos: "DEF", price: 5.0 },
    { name: "Jesús Gallardo",     pos: "DEF", price: 5.0 },
    { name: "Edson Álvarez",      pos: "MID", price: 6.5 },
    { name: "Héctor Herrera",     pos: "MID", price: 6.0 },
    { name: "Chucky Lozano",      pos: "MID", price: 7.0 },
    { name: "Orbelín Pineda",     pos: "MID", price: 5.5 },
    { name: "Roberto Alvarado",   pos: "MID", price: 5.5 },
    { name: "Raúl Jiménez",       pos: "FWD", price: 7.5 },
    { name: "Santiago Giménez",   pos: "FWD", price: 8.0 },
    { name: "Henry Martín",       pos: "FWD", price: 6.5 },
  ]},
  // ── 13. Japan ─────────────────────────────────────────────────────────────
  { name: "Japan", code: "JPN", players: [
    { name: "Zion Suzuki",         pos: "GK",  price: 4.5 },
    { name: "Shuichi Gonda",       pos: "GK",  price: 4.5 },
    { name: "Takehiro Tomiyasu",   pos: "DEF", price: 5.5 },
    { name: "Ko Itakura",          pos: "DEF", price: 5.5 },
    { name: "Maya Yoshida",        pos: "DEF", price: 5.0 },
    { name: "Miki Yamane",         pos: "DEF", price: 5.0 },
    { name: "Yuto Nagatomo",       pos: "DEF", price: 5.0 },
    { name: "Wataru Endo",         pos: "MID", price: 6.5 },
    { name: "Hidemasa Morita",     pos: "MID", price: 6.0 },
    { name: "Kaoru Mitoma",        pos: "MID", price: 8.0 },
    { name: "Takefusa Kubo",       pos: "MID", price: 7.5 },
    { name: "Daichi Kamada",       pos: "MID", price: 6.5 },
    { name: "Ayase Ueda",          pos: "FWD", price: 7.0 },
    { name: "Yuya Osako",          pos: "FWD", price: 6.0 },
    { name: "Ritsu Doan",          pos: "FWD", price: 6.5 },
  ]},
  // ── 14. Morocco ───────────────────────────────────────────────────────────
  { name: "Morocco", code: "MAR", players: [
    { name: "Yassine Bounou",     pos: "GK",  price: 5.5 },
    { name: "Munir Mohamedi",     pos: "GK",  price: 4.5 },
    { name: "Achraf Hakimi",      pos: "DEF", price: 8.0 },
    { name: "Romain Saïss",       pos: "DEF", price: 5.5 },
    { name: "Nayef Aguerd",       pos: "DEF", price: 6.0 },
    { name: "Noussair Mazraoui",  pos: "DEF", price: 6.0 },
    { name: "Achraf Dari",        pos: "DEF", price: 5.5 },
    { name: "Sofyan Amrabat",     pos: "MID", price: 7.0 },
    { name: "Hakim Ziyech",       pos: "MID", price: 7.5 },
    { name: "Azzedine Ounahi",    pos: "MID", price: 6.5 },
    { name: "Bilal El Khannouss", pos: "MID", price: 6.0 },
    { name: "Abde Ezzalzouli",    pos: "MID", price: 6.0 },
    { name: "Youssef En-Nesyri",  pos: "FWD", price: 8.0 },
    { name: "Sofiane Boufal",     pos: "FWD", price: 6.5 },
    { name: "Ayoub El Kaabi",     pos: "FWD", price: 6.5 },
  ]},
  // ── 15. Senegal ───────────────────────────────────────────────────────────
  { name: "Senegal", code: "SEN", players: [
    { name: "Édouard Mendy",       pos: "GK",  price: 5.0 },
    { name: "Alfred Gomis",        pos: "GK",  price: 4.5 },
    { name: "Kalidou Koulibaly",   pos: "DEF", price: 6.5 },
    { name: "Abdou Diallo",        pos: "DEF", price: 5.5 },
    { name: "Moussa Niakhaté",     pos: "DEF", price: 5.5 },
    { name: "Youssouf Sabaly",     pos: "DEF", price: 5.5 },
    { name: "Fodé Ballo-Touré",    pos: "DEF", price: 5.0 },
    { name: "Idrissa Gana Gueye", pos: "MID", price: 6.5 },
    { name: "Cheikhou Kouyaté",    pos: "MID", price: 6.0 },
    { name: "Pape Guèye",          pos: "MID", price: 5.5 },
    { name: "Lamine Camara",       pos: "MID", price: 6.0 },
    { name: "Iliman Ndiaye",       pos: "MID", price: 6.5 },
    { name: "Sadio Mané",          pos: "FWD", price: 8.5 },
    { name: "Nicolas Jackson",     pos: "FWD", price: 8.0 },
    { name: "Ismaila Sarr",        pos: "FWD", price: 7.0 },
  ]},
  // ── 16. Australia ─────────────────────────────────────────────────────────
  { name: "Australia", code: "AUS", players: [
    { name: "Mat Ryan",            pos: "GK",  price: 4.5 },
    { name: "Andrew Redmayne",     pos: "GK",  price: 4.0 },
    { name: "Harry Souttar",       pos: "DEF", price: 5.5 },
    { name: "Miloš Degenek",       pos: "DEF", price: 5.0 },
    { name: "Bailey Wright",       pos: "DEF", price: 5.0 },
    { name: "Joel King",           pos: "DEF", price: 5.0 },
    { name: "Aziz Behich",         pos: "DEF", price: 5.0 },
    { name: "Aaron Mooy",          pos: "MID", price: 5.5 },
    { name: "Jackson Irvine",      pos: "MID", price: 5.5 },
    { name: "Riley McGree",        pos: "MID", price: 5.5 },
    { name: "Ajdin Hrustic",       pos: "MID", price: 5.5 },
    { name: "Martin Boyle",        pos: "MID", price: 5.5 },
    { name: "Mathew Leckie",       pos: "FWD", price: 6.0 },
    { name: "Mitch Duke",          pos: "FWD", price: 6.0 },
    { name: "Garang Kuol",         pos: "FWD", price: 6.0 },
  ]},
  // ── 17. Canada ────────────────────────────────────────────────────────────
  { name: "Canada", code: "CAN", players: [
    { name: "Milan Borjan",        pos: "GK",  price: 4.5 },
    { name: "Maxime Crépeau",      pos: "GK",  price: 4.5 },
    { name: "Alphonso Davies",     pos: "DEF", price: 7.5 },
    { name: "Alistair Johnston",   pos: "DEF", price: 5.5 },
    { name: "Kamal Miller",        pos: "DEF", price: 5.0 },
    { name: "Derek Cornelius",     pos: "DEF", price: 5.0 },
    { name: "Sam Adekugbe",        pos: "DEF", price: 5.0 },
    { name: "Stephen Eustáquio",   pos: "MID", price: 6.5 },
    { name: "Atiba Hutchinson",    pos: "MID", price: 5.5 },
    { name: "Jonathan Osorio",     pos: "MID", price: 5.5 },
    { name: "Tajon Buchanan",      pos: "MID", price: 6.0 },
    { name: "Ismaël Koné",         pos: "MID", price: 6.0 },
    { name: "Jonathan David",      pos: "FWD", price: 9.0 },
    { name: "Cyle Larin",          pos: "FWD", price: 6.5 },
    { name: "Liam Millar",         pos: "FWD", price: 6.0 },
  ]},
  // ── 18. Ecuador ───────────────────────────────────────────────────────────
  { name: "Ecuador", code: "ECU", players: [
    { name: "Hernán Galíndez",     pos: "GK",  price: 4.5 },
    { name: "Alexander Domínguez", pos: "GK",  price: 4.5 },
    { name: "Piero Hincapié",      pos: "DEF", price: 6.0 },
    { name: "Byron Castillo",      pos: "DEF", price: 5.5 },
    { name: "Félix Torres",        pos: "DEF", price: 5.5 },
    { name: "Jackson Porozo",      pos: "DEF", price: 5.0 },
    { name: "Pervis Estupiñán",    pos: "DEF", price: 6.0 },
    { name: "Moisés Caicedo",      pos: "MID", price: 8.0 },
    { name: "Carlos Gruezo",       pos: "MID", price: 5.5 },
    { name: "Gonzalo Plata",       pos: "MID", price: 6.0 },
    { name: "Jeremy Sarmiento",    pos: "MID", price: 5.5 },
    { name: "Ángel Mena",          pos: "MID", price: 5.5 },
    { name: "Enner Valencia",      pos: "FWD", price: 7.5 },
    { name: "Michael Estrada",     pos: "FWD", price: 6.5 },
    { name: "Djorkaeff Reasco",    pos: "FWD", price: 6.0 },
  ]},
  // ── 19. Uruguay ───────────────────────────────────────────────────────────
  { name: "Uruguay", code: "URU", players: [
    { name: "Sergio Rochet",          pos: "GK",  price: 4.5 },
    { name: "Fernando Muslera",       pos: "GK",  price: 4.5 },
    { name: "Ronald Araújo",          pos: "DEF", price: 7.0 },
    { name: "José María Giménez",     pos: "DEF", price: 6.5 },
    { name: "Diego Godín",            pos: "DEF", price: 5.5 },
    { name: "Mathías Olivera",        pos: "DEF", price: 6.0 },
    { name: "Nahitan Nández",         pos: "DEF", price: 5.5 },
    { name: "Federico Valverde",      pos: "MID", price: 8.5 },
    { name: "Rodrigo Bentancur",      pos: "MID", price: 7.0 },
    { name: "Manuel Ugarte",          pos: "MID", price: 7.0 },
    { name: "Giorgian de Arrascaeta", pos: "MID", price: 7.0 },
    { name: "Lucas Torreira",         pos: "MID", price: 6.5 },
    { name: "Darwin Núñez",           pos: "FWD", price: 9.0 },
    { name: "Luis Suárez",            pos: "FWD", price: 7.5 },
    { name: "Facundo Torres",         pos: "FWD", price: 7.0 },
  ]},
  // ── 20. Switzerland ───────────────────────────────────────────────────────
  { name: "Switzerland", code: "SUI", players: [
    { name: "Gregor Kobel",       pos: "GK",  price: 5.0 },
    { name: "Yann Sommer",        pos: "GK",  price: 5.0 },
    { name: "Manuel Akanji",      pos: "DEF", price: 6.5 },
    { name: "Fabian Schär",       pos: "DEF", price: 6.0 },
    { name: "Nico Elvedi",        pos: "DEF", price: 5.5 },
    { name: "Ricardo Rodriguez",  pos: "DEF", price: 5.5 },
    { name: "Silvan Widmer",      pos: "DEF", price: 5.5 },
    { name: "Granit Xhaka",       pos: "MID", price: 7.0 },
    { name: "Remo Freuler",       pos: "MID", price: 6.5 },
    { name: "Xherdan Shaqiri",    pos: "MID", price: 6.5 },
    { name: "Denis Zakaria",      pos: "MID", price: 6.0 },
    { name: "Dan Ndoye",          pos: "MID", price: 6.0 },
    { name: "Breel Embolo",       pos: "FWD", price: 7.5 },
    { name: "Ruben Vargas",       pos: "FWD", price: 7.0 },
    { name: "Zeki Amdouni",       pos: "FWD", price: 6.5 },
  ]},
  // ── 21. Poland ────────────────────────────────────────────────────────────
  { name: "Poland", code: "POL", players: [
    { name: "Wojciech Szczęsny",    pos: "GK",  price: 5.0 },
    { name: "Łukasz Fabiański",     pos: "GK",  price: 4.5 },
    { name: "Kamil Glik",           pos: "DEF", price: 5.0 },
    { name: "Jan Bednarek",         pos: "DEF", price: 5.5 },
    { name: "Jakub Kiwior",         pos: "DEF", price: 5.5 },
    { name: "Matty Cash",           pos: "DEF", price: 6.0 },
    { name: "Bartosz Bereszyński",  pos: "DEF", price: 5.0 },
    { name: "Piotr Zieliński",      pos: "MID", price: 7.5 },
    { name: "Grzegorz Krychowiak",  pos: "MID", price: 6.0 },
    { name: "Sebastian Szymański",  pos: "MID", price: 6.5 },
    { name: "Przemysław Frankowski",pos: "MID", price: 6.0 },
    { name: "Nicola Zalewski",      pos: "MID", price: 6.0 },
    { name: "Robert Lewandowski",   pos: "FWD", price: 9.5 },
    { name: "Arkadiusz Milik",      pos: "FWD", price: 7.0 },
    { name: "Karol Świderski",      pos: "FWD", price: 6.5 },
  ]},
  // ── 22. Denmark ───────────────────────────────────────────────────────────
  { name: "Denmark", code: "DEN", players: [
    { name: "Kasper Schmeichel",   pos: "GK",  price: 5.0 },
    { name: "Oliver Christensen",  pos: "GK",  price: 4.5 },
    { name: "Simon Kjær",          pos: "DEF", price: 5.5 },
    { name: "Andreas Christensen", pos: "DEF", price: 6.5 },
    { name: "Joachim Andersen",    pos: "DEF", price: 6.0 },
    { name: "Joakim Mæhle",        pos: "DEF", price: 6.0 },
    { name: "Víctor Nelsson",       pos: "DEF", price: 5.5 },
    { name: "Christian Eriksen",   pos: "MID", price: 7.5 },
    { name: "Pierre-Emile Højbjerg",pos:"MID", price: 7.0 },
    { name: "Thomas Delaney",      pos: "MID", price: 6.5 },
    { name: "Mikkel Damsgaard",    pos: "MID", price: 6.5 },
    { name: "Jesper Lindstrøm",    pos: "MID", price: 6.5 },
    { name: "Rasmus Højlund",      pos: "FWD", price: 8.5 },
    { name: "Jonas Wind",          pos: "FWD", price: 7.0 },
    { name: "Andreas Cornelius",   pos: "FWD", price: 6.5 },
  ]},
  // ── 23. Serbia ────────────────────────────────────────────────────────────
  { name: "Serbia", code: "SRB", players: [
    { name: "Predrag Rajković",        pos: "GK",  price: 5.0 },
    { name: "Vanja Milinković-Savić",  pos: "GK",  price: 4.5 },
    { name: "Strahinja Pavlović",      pos: "DEF", price: 5.5 },
    { name: "Nikola Milenković",       pos: "DEF", price: 5.5 },
    { name: "Miloš Veljković",         pos: "DEF", price: 5.0 },
    { name: "Filip Mladenović",        pos: "DEF", price: 5.0 },
    { name: "Strahinja Eraković",      pos: "DEF", price: 5.5 },
    { name: "Sergej Milinković-Savić", pos: "MID", price: 8.0 },
    { name: "Saša Lukić",              pos: "MID", price: 6.5 },
    { name: "Filip Kostić",            pos: "MID", price: 7.0 },
    { name: "Dušan Tadić",             pos: "MID", price: 6.5 },
    { name: "Lazar Samardžić",         pos: "MID", price: 7.0 },
    { name: "Aleksandar Mitrović",     pos: "FWD", price: 9.0 },
    { name: "Dušan Vlahović",          pos: "FWD", price: 8.5 },
    { name: "Luka Jović",              pos: "FWD", price: 7.0 },
  ]},
  // ── 24. South Korea ───────────────────────────────────────────────────────
  { name: "South Korea", code: "KOR", players: [
    { name: "Kim Seung-gyu",      pos: "GK",  price: 4.5 },
    { name: "Jo Hyeon-woo",       pos: "GK",  price: 4.5 },
    { name: "Kim Min-jae",        pos: "DEF", price: 7.0 },
    { name: "Kim Young-gwon",     pos: "DEF", price: 5.0 },
    { name: "Jung Seung-hyun",    pos: "DEF", price: 5.0 },
    { name: "Kim Jin-su",         pos: "DEF", price: 5.0 },
    { name: "Yoon Jong-gyu",      pos: "DEF", price: 5.0 },
    { name: "Son Heung-min",      pos: "MID", price: 9.5 },
    { name: "Hwang In-beom",      pos: "MID", price: 6.5 },
    { name: "Lee Jae-sung",       pos: "MID", price: 6.0 },
    { name: "Lee Kang-in",        pos: "MID", price: 7.5 },
    { name: "Paik Seung-ho",      pos: "MID", price: 5.5 },
    { name: "Hwang Hee-chan",      pos: "FWD", price: 7.5 },
    { name: "Cho Gue-sung",       pos: "FWD", price: 7.0 },
    { name: "Oh Hyeon-gyu",       pos: "FWD", price: 6.5 },
  ]},
  // ── 25. Ghana ─────────────────────────────────────────────────────────────
  { name: "Ghana", code: "GHA", players: [
    { name: "Lawrence Ati-Zigi",  pos: "GK",  price: 4.0 },
    { name: "Joseph Wollacott",   pos: "GK",  price: 4.0 },
    { name: "Daniel Amartey",     pos: "DEF", price: 4.5 },
    { name: "Alexander Djiku",    pos: "DEF", price: 4.5 },
    { name: "Tariq Lamptey",      pos: "DEF", price: 5.5 },
    { name: "Baba Rahman",        pos: "DEF", price: 4.5 },
    { name: "Gideon Mensah",      pos: "DEF", price: 4.5 },
    { name: "Thomas Partey",      pos: "MID", price: 7.0 },
    { name: "André Ayew",         pos: "MID", price: 5.5 },
    { name: "Jordan Ayew",        pos: "MID", price: 5.5 },
    { name: "Mohammed Kudus",     pos: "MID", price: 7.5 },
    { name: "Osman Bukari",       pos: "MID", price: 5.5 },
    { name: "Iñaki Williams",     pos: "FWD", price: 7.0 },
    { name: "Antoine Semenyo",    pos: "FWD", price: 6.5 },
    { name: "Ernest Nuamah",      pos: "FWD", price: 6.0 },
  ]},
  // ── 26. Cameroon ──────────────────────────────────────────────────────────
  { name: "Cameroon", code: "CMR", players: [
    { name: "André Onana",              pos: "GK",  price: 5.5 },
    { name: "Devis Epassy",             pos: "GK",  price: 4.0 },
    { name: "Collins Fai",              pos: "DEF", price: 4.5 },
    { name: "Michael Ngadeu-Ngadjui",   pos: "DEF", price: 4.5 },
    { name: "Jean-Charles Castelletto", pos: "DEF", price: 4.5 },
    { name: "Nouhou",                   pos: "DEF", price: 4.5 },
    { name: "Ambroise Oyongo",          pos: "DEF", price: 4.5 },
    { name: "Frank Zambo Anguissa",     pos: "MID", price: 7.0 },
    { name: "Samuel Gouet",             pos: "MID", price: 5.5 },
    { name: "Martin Hongla",            pos: "MID", price: 5.5 },
    { name: "Moumi Ngamaleu",           pos: "MID", price: 5.5 },
    { name: "Gaël Ondoua",              pos: "MID", price: 5.0 },
    { name: "Vincent Aboubakar",        pos: "FWD", price: 7.0 },
    { name: "Bryan Mbeumo",             pos: "FWD", price: 7.5 },
    { name: "Karl Toko Ekambi",         pos: "FWD", price: 6.5 },
  ]},
  // ── 27. Tunisia ───────────────────────────────────────────────────────────
  { name: "Tunisia", code: "TUN", players: [
    { name: "Aymen Dahmen",            pos: "GK",  price: 4.0 },
    { name: "Béchir Ben Said",         pos: "GK",  price: 4.0 },
    { name: "Dylan Bronn",             pos: "DEF", price: 4.5 },
    { name: "Montassar Talbi",         pos: "DEF", price: 4.5 },
    { name: "Wajdi Kechrida",          pos: "DEF", price: 4.5 },
    { name: "Ali Maaloul",             pos: "DEF", price: 5.0 },
    { name: "Nader Ghandri",           pos: "DEF", price: 4.5 },
    { name: "Aïssa Laïdouni",          pos: "MID", price: 5.5 },
    { name: "Ellyes Skhiri",           pos: "MID", price: 6.0 },
    { name: "Ferjani Sassi",           pos: "MID", price: 5.5 },
    { name: "Hannibal Mejbri",         pos: "MID", price: 6.0 },
    { name: "Naïm Sliti",              pos: "MID", price: 5.5 },
    { name: "Wahbi Khazri",            pos: "FWD", price: 6.5 },
    { name: "Issam Jebali",            pos: "FWD", price: 6.0 },
    { name: "Seifeddine Jaziri",       pos: "FWD", price: 6.0 },
  ]},
  // ── 28. Saudi Arabia ──────────────────────────────────────────────────────
  { name: "Saudi Arabia", code: "KSA", players: [
    { name: "Mohammed Al-Owais",    pos: "GK",  price: 4.5 },
    { name: "Fawaz Al-Qarni",       pos: "GK",  price: 4.0 },
    { name: "Saud Abdulhamid",      pos: "DEF", price: 5.0 },
    { name: "Ali Al-Bulayhi",       pos: "DEF", price: 5.0 },
    { name: "Hassan Tambakti",      pos: "DEF", price: 4.5 },
    { name: "Yasser Al-Shahrani",   pos: "DEF", price: 5.0 },
    { name: "Mohammed Al-Breik",    pos: "DEF", price: 4.5 },
    { name: "Salman Al-Faraj",      pos: "MID", price: 5.5 },
    { name: "Mohammed Kanno",       pos: "MID", price: 5.5 },
    { name: "Salem Al-Dawsari",     pos: "MID", price: 6.5 },
    { name: "Abdullah Al-Hamdan",   pos: "MID", price: 5.5 },
    { name: "Hattan Bahebri",       pos: "MID", price: 5.0 },
    { name: "Firas Al-Buraikan",    pos: "FWD", price: 6.5 },
    { name: "Saleh Al-Shehri",      pos: "FWD", price: 6.0 },
    { name: "Abdullah Al-Khaibari", pos: "FWD", price: 5.5 },
  ]},
  // ── 29. Iran ──────────────────────────────────────────────────────────────
  { name: "Iran", code: "IRN", players: [
    { name: "Alireza Beiranvand",    pos: "GK",  price: 4.5 },
    { name: "Hossein Hosseini",      pos: "GK",  price: 4.0 },
    { name: "Shoja Khalilzadeh",     pos: "DEF", price: 4.5 },
    { name: "Majid Hosseini",        pos: "DEF", price: 4.5 },
    { name: "Milad Mohammadi",       pos: "DEF", price: 4.5 },
    { name: "Roozbeh Cheshmi",       pos: "DEF", price: 4.5 },
    { name: "Sadegh Moharrami",      pos: "DEF", price: 4.5 },
    { name: "Saeid Ezatolahi",       pos: "MID", price: 5.5 },
    { name: "Ali Gholizadeh",        pos: "MID", price: 5.5 },
    { name: "Alireza Jahanbakhsh",   pos: "MID", price: 6.0 },
    { name: "Mehdi Torabi",          pos: "MID", price: 5.5 },
    { name: "Saman Ghoddos",         pos: "MID", price: 5.5 },
    { name: "Mehdi Taremi",          pos: "FWD", price: 7.5 },
    { name: "Sardar Azmoun",         pos: "FWD", price: 7.0 },
    { name: "Karim Ansarifard",      pos: "FWD", price: 6.0 },
  ]},
  // ── 30. Costa Rica ────────────────────────────────────────────────────────
  { name: "Costa Rica", code: "CRC", players: [
    { name: "Keylor Navas",      pos: "GK",  price: 5.0 },
    { name: "Patrick Sequeira",  pos: "GK",  price: 4.0 },
    { name: "Bryan Oviedo",      pos: "DEF", price: 4.5 },
    { name: "Keysher Fuller",    pos: "DEF", price: 4.5 },
    { name: "Oscar Duarte",      pos: "DEF", price: 4.5 },
    { name: "Kendall Waston",    pos: "DEF", price: 4.5 },
    { name: "Ronald Matarrita",  pos: "DEF", price: 4.5 },
    { name: "Celso Borges",      pos: "MID", price: 5.5 },
    { name: "Yeltsin Tejeda",    pos: "MID", price: 5.0 },
    { name: "Rándall Leal",      pos: "MID", price: 5.0 },
    { name: "Orlando Galo",      pos: "MID", price: 5.0 },
    { name: "Douglas Sequeira",  pos: "MID", price: 5.0 },
    { name: "Joel Campbell",     pos: "FWD", price: 6.5 },
    { name: "Johan Venegas",     pos: "FWD", price: 6.0 },
    { name: "Manfred Ugalde",    pos: "FWD", price: 6.5 },
  ]},
  // ── 31. Wales ─────────────────────────────────────────────────────────────
  { name: "Wales", code: "WAL", players: [
    { name: "Wayne Hennessey",  pos: "GK",  price: 4.5 },
    { name: "Danny Ward",       pos: "GK",  price: 4.0 },
    { name: "Ben Davies",       pos: "DEF", price: 5.0 },
    { name: "Joe Rodon",        pos: "DEF", price: 5.0 },
    { name: "Chris Mepham",     pos: "DEF", price: 4.5 },
    { name: "Connor Roberts",   pos: "DEF", price: 5.0 },
    { name: "Neco Williams",    pos: "DEF", price: 4.5 },
    { name: "Aaron Ramsey",     pos: "MID", price: 6.0 },
    { name: "Joe Allen",        pos: "MID", price: 5.5 },
    { name: "Harry Wilson",     pos: "MID", price: 5.5 },
    { name: "Dylan Levitt",     pos: "MID", price: 5.0 },
    { name: "Rubin Colwill",    pos: "MID", price: 5.5 },
    { name: "Gareth Bale",      pos: "FWD", price: 7.5 },
    { name: "Brennan Johnson",  pos: "FWD", price: 7.0 },
    { name: "Kieffer Moore",    pos: "FWD", price: 6.5 },
  ]},
  // ── 32. Qatar ─────────────────────────────────────────────────────────────
  { name: "Qatar", code: "QAT", players: [
    { name: "Meshaal Barsham",     pos: "GK",  price: 4.0 },
    { name: "Saad Al-Sheeb",       pos: "GK",  price: 4.0 },
    { name: "Bassam Al-Rawi",      pos: "DEF", price: 4.0 },
    { name: "Pedro Miguel",        pos: "DEF", price: 4.5 },
    { name: "Tarek Salman",        pos: "DEF", price: 4.0 },
    { name: "Mohammed Waad",       pos: "DEF", price: 4.0 },
    { name: "Abdelkarim Hassan",   pos: "DEF", price: 4.5 },
    { name: "Akram Afif",          pos: "MID", price: 6.0 },
    { name: "Hassan Al-Haydos",    pos: "MID", price: 5.5 },
    { name: "Karim Boudiaf",       pos: "MID", price: 5.0 },
    { name: "Boualem Khoukhi",     pos: "MID", price: 5.0 },
    { name: "Ismaeel Mohammad",    pos: "MID", price: 4.5 },
    { name: "Almoez Ali",          pos: "FWD", price: 6.0 },
    { name: "Mohammed Muntari",    pos: "FWD", price: 5.5 },
    { name: "Khalid Muneer",       pos: "FWD", price: 5.0 },
  ]},
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("═══════════════════════════════════════════════════════════════");
  console.log("  FIFA World Cup 2026 — Static Player Seed");
  console.log("═══════════════════════════════════════════════════════════════\n");

  const totalDefined = NATIONS.reduce((s, n) => s + n.players.length, 0);
  console.log(`Defined: ${NATIONS.length} nations, ${totalDefined} players\n`);

  console.log("Clearing existing players & team rosters…");
  await db.execute(sql`DELETE FROM team_players`);
  await db.execute(sql`DELETE FROM players`);
  await db.execute(sql`ALTER SEQUENCE players_id_seq RESTART WITH 1`);

  const now = new Date();
  let inserted = 0;

  console.log("Seeding nations…\n");
  for (const nation of NATIONS) {
    const rows = nation.players.map(p => ({
      name: p.name,
      position: p.pos as string,
      club: nation.name,
      clubShortName: nation.code,
      nationality: nation.name,
      price: p.price,
      totalPoints: 0,
      form: 0,
      selected: 0,
      goalsScored: 0,
      assists: 0,
      cleanSheets: 0,
      cachedFromApi: false,
      cachedAt: now,
      imageUrl: null as string | null,
    }));
    await db.insert(playersTable).values(rows);
    inserted += rows.length;
    console.log(`  ✔ ${nation.code} ${nation.name}: ${rows.length} players`);
  }

  console.log("\nResetting team budgets to £100m…");
  await db.execute(sql`UPDATE teams SET budget = 100, captain_id = NULL, vice_captain_id = NULL`);

  console.log("\n═══════════════════════════════════════════════════════════════");
  console.log(`  Done. ${inserted} players across ${NATIONS.length} nations added.`);
  console.log("═══════════════════════════════════════════════════════════════");
}

main().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
